//
//  SearchJokeManagerMock.swift
//  JokeGenTests
//
//  Created by Leonid Kokhnovych on 2018-05-10.
//  Copyright © 2018 Leonid Kokhnovych. All rights reserved.
//

import Foundation
import ReactiveSwift
@testable import JokeGen

// Generated by https://github.com/seanhenry/SwiftMockGeneratorForXcode
class SearchJokeManagerMock: SearchJokeManagerType {
    var invokedSearch = false
    var invokedSearchCount = 0
    var invokedSearchParameters: (query: String, Void)?
    var invokedSearchParametersList = [(query: String, Void)]()
    var stubbedSearchResult: SignalProducer<SearchJokeQuery.Data.Joke, SearchJokeManagerError>!
    func search(by query: String) -> SignalProducer<SearchJokeQuery.Data.Joke, SearchJokeManagerError> {
        invokedSearch = true
        invokedSearchCount += 1
        invokedSearchParameters = (query, ())
        invokedSearchParametersList.append((query, ()))
        return stubbedSearchResult
    }
}
